### ISSUE TITLE
[Issue] Unable to scroll window when content fills note 

### ISSUE THREAD

**Issue by thejasonparker** [Savjee/bearclaw#13]
When I paste copy into the window if it is more than the window size I am unable to scroll to view and edit it. 

You can see the issue in this video: https://cl.ly/943bc8

It would be useful to be able to scroll vertically and maybe resize the window area to fit in with different screen sizes.

Setup:
MacBook Pro (Retina, 13-inch, Early 2015)
MacOS Mojave 10.14.5 (18F132)
Bearclaw 1.1.0

**Comment by Savjee** [comment]
Sorry it took me so long to reply.
This is definitely a bug I'll look into. Keep you posted!

**Comment by thejasonparker** [comment]
No worries. Thanks for the reply and I look forward to the update 👍

**Comment by Savjee** [comment]
Can you try this build to see if the problem is fixed?
https://github.com/Savjee/bearclaw/releases/tag/v1.1.0-beta

Thanks!

**Comment by thejasonparker** [comment]
It works perfectly. Thanks for adding this to a great utility :)

**Comment by Savjee** [comment]
Thanks for testing! I pushed the update to everyone
151e51c0c66ea09628dee07428fbc0d67557094a
