### ISSUE TITLE
[Issue] Note being lost after laptop reboot

### ISSUE THREAD

**Issue by thejasonparker** [Savjee/bearclaw#14]
I'm not sure if BearClaw is actually meant to save the note and still be available after a reboot but I am presuming it should. If not could this be added as a feature? Thanks :)

Setup:
MacBook Pro (Retina, 13-inch, Early 2015)
MacOS Mojave 10.14.5 (18F132)
Bearclaw 1.1.0

**Comment by Savjee** [comment]
For me this isn't really an issue. Bearclaw is only intended to write up a quick note and send it to Bear for safekeeping.
