### ISSUE TITLE
Append text instead of creating a new note.

### ISSUE THREAD

**Issue by ignazioc** [Savjee/bearclaw#16]
Hi,
I found this repository in one reddit conversation https://www.reddit.com/r/bearapp/comments/citraa/feature_request_sticky_note_on_the_status_bar/
I would like to add some features to this app to make it possible to use for journaling. 
The bearclaw app would create max 1 note per day, each additional text added on the same day should be appended to the same note maybe below a dashed line
```
---------- 10:45 AM
text tex text text
text tex text text
---------- 9:00 PM
text tex text text
text tex text text
````

I also have in mind some othe funcionalities like parsing the `#tags` and `todos` but before I start writing the code I wanted to ask if you like the idea, if you think this could become the main use-case of the app or if you think _both_ use cases should be supported (journaling + the current flow)

**Comment by Savjee** [comment]
Hi,

This wasn't a use case I envisioned when building Bearclaw, but I'm not opposed to adding it. We need to be careful with building the UI. 

I think the default/main action should still be "create new note". However, we could add a segment control on top to switch modes. Once switched, it would stay in journaling mode.

Let me know what you think.

About parsing the #tags: sounds great! Not sure how you're going to fix the todos though?

**Comment by ignazioc** [comment]
Great 👍  I'll keep in mind that for you the "create new note" is the main use case.
`Todos` e `tags` are just random ideas...I have not all the details in mind. I keep a note with my `todos`, it would be cool to use bearcraw to add an entry to it just hitting a shortcut and then typing "buy the milk"
